apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Optional: Set a unified namespace for your desktop deployment
# namespace: remote-desktop

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
